[package]
name = "wasminspect-wasi-macro"
version = "0.2.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
witx = "0.9.0"
quote = "1.0"

[badges]
maintenance = { status = "actively-developed" }
