[package]
name = "wasminspect-wasi"
version = "0.2.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[dependencies]
wasi-common = "0.22.0"
wiggle = "0.22.0"
log = "0.4"
wasminspect-vm = { path = "../vm" }
wasminspect-wasi-macro = { path = "./macro" }
wasmparser = "0.76.0"
