[package]
name = "wasminspect-wasi"
version = "0.2.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[dependencies]
wasi-common = "0.16.0"
wiggle = "0.16.0"
wasminspect-vm = { path = "../vm" }
wasmparser = "0.76.0"
